### ISSUE TITLE
Topic ARN format in Billing API

### ISSUE THREAD

**Issue by SethThomas** [AnomalyInnovations/serverless-stack-demo-ext-api#8]
https://github.com/AnomalyInnovations/serverless-stack-demo-ext-api/blob/5e0cd8118ae76bbfe1c1b6d006b528f5db7b9ae0/services/billing-api/billing.js#L41

The TopicArn in billing.js appears to be the topic name, not an ARN:

Shouldn't this field be formatted as an ARN?

`TopicName: arn:aws:sns:<REGION>:<AWS ID>:<TOPIC NAME>`

**Comment by jayair** [comment]
Good catch. We were trying to use it as a sample but it should've been what we have in the environment variable:

https://github.com/AnomalyInnovations/serverless-stack-demo-ext-api/pull/10
